name: e_commerce_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter 

  google_fonts: ^6.3.2
  flutter_svg: ^2.1.1 
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.2.0
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  auto_route: ^11.0.0
  talker_dio_logger: ^5.1.12
  talker_flutter: ^5.1.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.11.0 
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0


flutter:   
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: TRYGrtsk
      fonts:
        - asset: lib/assets/fonts/TRYGrtsk-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/TRYGrtsk-Bold.ttf
          weight: 700

  

# dependency_overrides:
#   # هذه الإصدارات تحل التعارض مع flutter_test
#   test: ^1.24.3
#   test_api: ^0.7.7
#   matcher: ^0.12.17
#   analyzer: ^8.4.1
#   # لاحظ: لا تضع flutter_lints هنا