name: e_commerce_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter 

  google_fonts: ^6.3.2
  flutter_svg: ^2.1.1 
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.2.0
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.9.0
  slang_build_runner: ^4.11.0 

flutter:   
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: TRYGrtsk
      fonts:
        - asset: assets/fonts/TRYGrtsk-Regular.ttf
        - asset: assets/fonts/TRYGrtsk-Bold.ttf

  
